"""empty message

Revision ID: 244992feed9f
Revises: 7097d26e1247
Create Date: 2024-06-01 15:59:19.840279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244992feed9f'
down_revision = '7097d26e1247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
