"""empty message

Revision ID: 245f557338d7
Revises: 003167402fba
Create Date: 2024-06-07 19:07:35.161111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245f557338d7'
down_revision = '003167402fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=False))
        batch_op.alter_column('room',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('room',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('message')

    # ### end Alembic commands ###
