"""empty message

Revision ID: 32d3ebe9e26b
Revises: 7d4056672d9d
Create Date: 2024-06-09 07:30:53.552199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d3ebe9e26b'
down_revision = '7d4056672d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_pet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'pet', ['sender_pet_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_pet_id')

    # ### end Alembic commands ###
