"""empty message

Revision ID: 47954ba21931
Revises: 8291d1f1df3e
Create Date: 2024-06-08 10:57:43.222431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47954ba21931'
down_revision = '8291d1f1df3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet1_id', sa.Integer(), nullable=False),
    sa.Column('pet2_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet1_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['pet2_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###
