"""empty message

Revision ID: 7786e1f5aeaf
Revises: 4e2b44ec1264
Create Date: 2024-05-28 20:19:42.490627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7786e1f5aeaf'
down_revision = '4e2b44ec1264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_profile_picture',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('picture_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], name='owner_profile_picture_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='owner_profile_picture_pkey')
    )
    # ### end Alembic commands ###
