"""empty message

Revision ID: 7d4056672d9d
Revises: cb50ab5a4263
Create Date: 2024-06-08 15:58:21.284061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4056672d9d'
down_revision = 'cb50ab5a4263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id'])
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###
