"""empty message

Revision ID: 8673d8554277
Revises: abcd3844048b
Create Date: 2024-06-07 18:12:01.965689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8673d8554277'
down_revision = 'abcd3844048b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=80), nullable=False),
    sa.Column('sender', sa.String(length=80), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
