"""empty message

Revision ID: 98032a0683dc
Revises: 3f9d7225805f
Create Date: 2024-05-24 14:05:22.799228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98032a0683dc'
down_revision = '3f9d7225805f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('breed', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pedigree', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pet_pkey')
    )
    # ### end Alembic commands ###
