"""empty message

Revision ID: a2a1be707b23
Revises: 2edea28df868
Create Date: 2024-05-25 20:22:04.753836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a1be707b23'
down_revision = '2edea28df868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'breed', ['breed_id'], ['id'])
        batch_op.create_foreign_key(None, 'owner', ['owner_id'], ['id'])
        batch_op.drop_column('breed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('breed_id')

    # ### end Alembic commands ###
