"""empty message

Revision ID: a7f8f867f450
Revises: b4973aa80fe7
Create Date: 2024-06-04 21:55:43.250133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f8f867f450'
down_revision = 'b4973aa80fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_pet_id', sa.Integer(), nullable=False),
    sa.Column('liked_pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liked_pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['liker_pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
