"""empty message

Revision ID: ffe9dffecd17
Revises: b10e9880daf1
Create Date: 2024-06-01 00:35:14.017204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe9dffecd17'
down_revision = 'b10e9880daf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pet', ['pet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pet_id')

    # ### end Alembic commands ###
